### ISSUE TITLE
Render animations at constant speed on command line (no gui)

### ISSUE THREAD

**Issue by hellocatfood** [savbran/evolvotron-fixed#1]
Is there a way to render an animation on the command line but have it play at a constant speed. When I run the following the command the animation renders:
```
evolvotron_render -f 50 --size 512x512 -j output.png < evolvotron_function_1.xml
```
However, it speeds up and then slows down towards the end. I'd like it to play at a constant speed.

I've noticed that `evolvotron_mutate` has the `--linear` option but using `evolvotron_mutuate` would change the original function, which is not what I want. 

The main evolvotron has the `--linear` option but it doesn't seem to do anything.

I'm using Evolvotron 0.7.1 and this function file: https://github.com/kmatylla/evolvotron-xml/blob/master/finished%20evolved%20patterns/stained%20windows%201.xml (I've tested it on many functions and still have the same result)

**Comment by savbran** [comment]
I'm maintaining the last version of Evolvotron code base as released by the original author (Tim Day) on [Evolvotron website](http://www.timday.com/share/evolvotron/index.htm), with just the addition of small patches to guarantee the successful build of the application when new Qt or other composing lib is updated. Just this. If you need to know if a specific feature is available in the app, please contact the original Author.
